### ISSUE TITLE
Add support for paginator template resolver

### ISSUE THREAD

**Issue by davidkudera** [Carrooi/Nette-NoGrid#8]
``` yaml
grid:
    paginator:
        template: @App\NoGrid\PaginatorTemplateResolver
```
